import { Alert, Box, Button, Chip, Container, Stack, Typography } from '@mui/material';
import ArrowDownwardIcon from '@mui/icons-material/ArrowDownward';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import { EducationView } from '../types';
import SectionHeader from '../components/SectionHeader';
import InfoCard from '../components/InfoCard';
import { Section } from '../types';

const hero = 'https://raw.githubusercontent.com/achamba-jpg/proyectos/main/proyecto%20angel%201.2/neandertalesorgin.jpg';
export default function HomePage({ data, onNavigate }: { data: EducationView; onNavigate: (section: Section) => void }) {
  return <><Box sx={{ minHeight: { xs: 610, md: 720 }, color: 'white', display: 'flex', alignItems: 'center', background: `linear-gradient(90deg,rgba(41,32,25,.94),rgba(41,32,25,.3)),url(${hero}) center/cover` }}><Container maxWidth="lg"><Chip label="Prehistoria + tecnología moderna" sx={{ bgcolor: 'secondary.main', color: '#292019', fontWeight: 800 }} /><Typography variant="h1" sx={{ maxWidth: 800, mt: 3, fontSize: { xs: '3rem', md: '5.6rem' } }}>El viaje que nos convirtió en humanos</Typography><Typography variant="h6" sx={{ maxWidth: 650, color: 'rgba(255,255,255,.86)', mb: 4 }}>Explora nuestra evolución, formas de vida, herramientas y los descubrimientos que explican quiénes somos.</Typography><Stack direction={{ xs: 'column', sm: 'row' }} spacing={2}><Button variant="contained" color="secondary" size="large" endIcon={<ArrowDownwardIcon />} onClick={() => onNavigate('evolucion')}>Explorar la historia</Button><Button variant="outlined" color="inherit" size="large" onClick={() => onNavigate('curiosidades')}>Datos curiosos</Button></Stack></Container></Box><Container maxWidth="lg" sx={{ py: 10 }}><SectionHeader eyebrow="Una guía educativa" title="Conoce las raíces de nuestra especie" text="Navega por las secciones para descubrir cómo vivían los Homo sapiens, qué herramientas utilizaban y qué huellas dejaron en la historia." centered /><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 3 }}><InfoCard icon="🧠" title="Evolución" text="Desde el origen en África hasta la expansión por el mundo." /><InfoCard icon="🏕️" title="Vida cotidiana" text="Alimentación, refugio, cooperación y cultura." /><InfoCard icon="🪨" title="Herramientas" text="Tecnologías primitivas que cambiaron la supervivencia." /></Box><Alert icon={<AutoAwesomeIcon />} severity="info" sx={{ mt: 7 }}>La información está preparada para consumirse desde endpoints REST y cuenta con datos de respaldo para esta demostración.</Alert></Container></>;
}
